packaging_format = 2

id = "ulogger"
name = "ulogger"
description.en = "Real-time collection of geolocation data, tracks viewing and management"
description.fr = "Géolocalisation en temps réel, gestion et affichage de traces"

version = "1.1~ynh1"

maintainers = [""]

[upstream]
license = "AGPL-3.0-only"
code = "https://github.com/bfabiszewski/ulogger-server"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ulogger"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["de", "en", "fr", "hu", "it", "pl"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/bfabiszewski/ulogger-server/archive/v1.1.zip"
        sha256 = "558b83214ef8dd04debf826d5330367d478ebd360a6dfd3c8328cded07c0e1a9"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.1-mysql"

    [resources.database]
    type = "mysql"
