#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

admin_pwd=$(openssl passwd -1 -salt xyz $password)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

# Create a dedicated php-fpm config
ynh_config_add_phpfpm

# Create a dedicated nginx config
ynh_config_add_nginx

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/config.php"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/config.php"

ynh_replace --match="\$enabled = false;" --replace="\$enabled = true;" --file="$install_dir/scripts/setup.php"

# Replace variables in SQL scripts
ynh_replace --match="__ADMIN__" --replace="$admin" --file="../conf/admin.sql"
ynh_replace --match="__ADMIN_PWD__" --replace="$admin_pwd" --file="../conf/admin.sql"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Finalizing installation..."

ynh_local_curl "/scripts/setup.php" "command=setup"

#Add the admin account to the database
ynh_mysql_db_shell < "../conf/admin.sql"
#Disable setup for security
ynh_replace --match="^\$enabled = true;" --replace="\$enabled = false;" --file="$install_dir/scripts/setup.php"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 755 -R $install_dir
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx $install_dir
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data $install_dir
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
